<a href="https://colab.research.google.com/github/JSJeong-me/Machine_Learning/blob/main/ML/3_train_test_data_sets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
x = np.random.randint(100)

In [ ]:
x

In [ ]:
x = np.random.rand(3, 5)

In [ ]:
x

In [ ]:
x[-2:]

In [ ]:
x = np.arange(1,11)

In [ ]:
x

In [ ]:
np.random.shuffle(x)

In [ ]:
x

In [ ]:
x

In [36]:
arr = np.array([[1,2],[3,4],[5,6]])

In [37]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
np.random.shuffle(arr)

In [45]:
arr

array([[1, 2],
       [5, 6],
       [3, 4]])

In [46]:
from sklearn.model_selection import train_test_split

In [52]:
y =range(5)

In [50]:
X = np.arange(10).reshape((5, 2))

In [51]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
y

range(0, 5)

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [60]:
X_train

array([[8, 9],
       [4, 5],
       [0, 1],
       [6, 7]])

In [61]:
X_test

array([[2, 3]])

In [62]:
y_train

[4, 2, 0, 3]

In [63]:
y_test

[1]