<a href="https://colab.research.google.com/github/JSJeong-me/Machine_Learning/blob/main/Python_Data_Types/u0707.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
scores = [[55, 66, 77, 88, 99],[76, 98, 35, 55, 97]]

In [2]:
type(scores)

list

In [3]:
import numpy as np


In [4]:
arr_scores = np.array(scores)

In [5]:
type(arr_scores)

numpy.ndarray

In [6]:
arr_scores.shape

(2, 5)

In [7]:
row = arr_scores.shape[0]

In [8]:
row

2

In [9]:
type(row)

int

In [14]:
arr_scores.

array([[55, 66, 77, 88, 99],
       [76, 98, 35, 55, 97]])

In [10]:
arr_scores.strides

(40, 8)

In [12]:
scores[0][0]

55

In [13]:
scores[0][1]

66

In [15]:
import pandas as pd


In [16]:
col = ["Kor", "Eng","Jan", "French", "Chn"]

In [17]:
inx = ["A_calss", "B_class"]

In [18]:
df = pd.DataFrame(arr_scores, columns=col, index=inx)

In [19]:
df.shape

(2, 5)

In [20]:
df.index

Index(['A_calss', 'B_class'], dtype='object')

In [21]:
df.columns

Index(['Kor', 'Eng', 'Jan', 'French', 'Chn'], dtype='object')

In [23]:
type(df.columns)

pandas.core.indexes.base.Index

In [24]:
col_df = df.columns.to_list()

In [25]:
col_df

['Kor', 'Eng', 'Jan', 'French', 'Chn']

In [26]:
type(col_df)

list

In [27]:
df

Kor  Eng  Jan  French  Chn
A_calss   55   66   77      88   99
B_class   76   98   35      55   97

In [37]:
df.iloc[ 0, -1]

99

In [32]:
df.loc["A_calss", "Kor"]

55

In [ ]:
t_val = (1024, 768, 3)

In [ ]:
width, height, RGB = t_val

In [ ]:
RGB

3

In [ ]:
def add(a, b):
  return a+b

In [ ]:
val = add(100, 200)

In [ ]:
val

300

In [ ]:
# def multi_func(a, b):
#   c = a+b
#   d = a*b
#   return c, d

In [1]:
import mul

In [2]:
x, y = mul.multi_func(2)

In [3]:
x

92

In [4]:
y

180

In [ ]:
mul_add, mul_mul = multu_func.multu_func(10, 15)

In [ ]:
mul_add

25

In [ ]:
mul_mul

150

In [ ]:
import multu_func

In [ ]:
import numpy

In [ ]:
import my_add

In [ ]:
add_val = my_add.add(200, 300)

In [ ]:
add_val

500

In [ ]:
import my_add

In [ ]:
import my_add

In [ ]:
add_val = my_add.divide(100, 300)

In [ ]:
add_val

400

In [ ]:
from my_add import divide

In [ ]:
add_val = divide(100, 300)

In [ ]:
add_val

400

In [ ]:
scores = [[67, 78, 56, 77, 88],[100, 98, 97, 96,88]]

In [ ]:
type(scores)

list

In [ ]:
import numpy

In [ ]:
arr_scores = numpy.array(scores)

In [ ]:
type(arr_scores)

numpy.ndarray

In [ ]:
arr_scores

array([[ 67,  78,  56,  77,  88],
       [100,  98,  97,  96,  88]])

In [ ]:
from numpy  import array

In [ ]:
arr_scores = array(scores)

In [ ]:
arr_scores

array([[ 67,  78,  56,  77,  88],
       [100,  98,  97,  96,  88]])

In [ ]:
scores = [[67, 78, 56, 77, 88],[100, 98, 97, 96,88]]

In [ ]:
scores

[[67, 78, 56, 77, 88], [100, 98, 97, 96, 88]]

In [ ]:
import pandas as pd

In [ ]:
idx = ["A_class", "B_class"]

In [ ]:
lang = ["Kor", "Eng", "Chn", "Jan", "French"]

In [ ]:
df = pd.DataFrame(scores, index=idx, columns=lang)

In [ ]:
df

Kor  Eng  Chn  Jan  French
A_class   67   78   56   77      88
B_class  100   98   97   96      88

In [ ]:
s_1 = df.loc["B_class"]

In [ ]:
type(s_1)

numpy.int64

In [ ]:
s_1

Kor       100
Eng        98
Chn        97
Jan        96
French     88
Name: B_class, dtype: int64

In [ ]:
scores[0][0]

67

In [ ]:
s_1

Kor       100
Eng        98
Chn        97
Jan        96
French     88
Name: B_class, dtype: int64